version: '3'
services:
  db:
    image: library/mysql:8.0.20
    container_name: mysql-standalone
    ports:
    - "3306:3306"
    environment:
      MYSQL_PASSWORD: marber1DEfact0
      MYSQL_ROOT_PASSWORD: marber1DEfact0
      MYSQL_DB: eva
      MSDATA: /var/lib/mysql/data/pgdata
    restart: always
  app:
    image: 147300/springboot-mysql:secondtry
    container_name: application
    ports:
    - "8080:8080"
    environment:
      MYSQL_HOST: db
    restart: always
    depends_on:
      - db
    links:
      - db
  nginx:
    image: library/nginx:1.17.2-alpine
    container_name: nginx
    volumes:
      - ./default.conf:/default.conf
    links:
      - app
    ports:
    - "8989:8989"
